services:
  app:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: learnproof-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/learnproof_db?connection_limit=15&pool_timeout=30
      - SOCIAL_DATABASE_URL=postgresql://user:password@db:5432/learnproof_db?connection_limit=15&pool_timeout=30
      - REDIS_URL=redis://cache:6379
      - NODE_ENV=production
      - MATRIX_HOMESERVER_URL=http://conduit:8008
      - MATRIX_CLIENT_HOMESERVER_URL=https://learnproofai.com
    env_file:
      - ./nodejs/.env
    volumes:
      - ./nodejs/media:/app/media
      - ./nodejs/prisma:/app/prisma
      - /home/ubuntu/.config/gcloud:/root/.config/gcloud:ro
    depends_on:
      - db
      - cache
      - conduit

  db:
    image: postgres:14-alpine
    container_name: learnproof-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=learnproof_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    container_name: learnproof-cache
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=https://learnproofai.com
        - VITE_GOOGLE_CLIENT_ID=557947080645-2iqd1t1h79b273ktjqthcg6q23k9pem1.apps.googleusercontent.com
        - VITE_ADMIN_EMAIL=nitin9699176009@gmail.com
    container_name: learnproof-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ./nodejs/media:/usr/share/nginx/html/media:ro
    depends_on:
      - app
      - conduit

  conduit:
    image: matrixconduit/matrix-conduit:latest
    container_name: learnproof-conduit
    restart: always
    environment:
      CONDUIT_SERVER_NAME: "learnproofai.com"
      CONDUIT_DATABASE_PATH: "/var/lib/matrix-conduit/"
      CONDUIT_PORT: "8008"
      CONDUIT_REGISTRATION_SHARED_SECRET: "1^ZzuyvWeCevsTm1*fTJEJ4KhcTRtdvod*_5QPLK0BGn*Lsx#H"
      CONDUIT_ALLOW_REGISTRATION: "false"
      CONDUIT_CONFIG: ""
    volumes:
      - conduit_data:/var/lib/matrix-conduit/

volumes:
  postgres_data:
  conduit_data:
